name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  publish:
    name: Build, release, and upload artifacts
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - run: cargo install cargo-pgo
      - run: ./build.ps1
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} ./redscript/target/x86_64-pc-windows-msvc/release/scc_lib.dll
